/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mis_clases;

import Codigos.Sql_usuarios;
import Codigos.Usuarios;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Usua = new javax.swing.JTextField();
        Apelli = new javax.swing.JTextField();
        Nom = new javax.swing.JTextField();
        Tel = new javax.swing.JTextField();
        Cont = new javax.swing.JPasswordField();
        Conf = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        CBXtipo_documento = new javax.swing.JComboBox<>();
        Num = new javax.swing.JTextField();
        Ciud = new javax.swing.JTextField();
        Dep = new javax.swing.JTextField();
        Corr = new javax.swing.JTextField();
        Direcc = new javax.swing.JTextField();
        Registrarse = new javax.swing.JButton();
        Volver = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));
        jPanel1.setForeground(new java.awt.Color(51, 255, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cooper Black", 2, 36)); // NOI18N
        jLabel1.setText("REGISTRAR");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 250, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 740, 110));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setText("Usuario :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setText("Contraseña :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setText("Confirmar :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel5.setText("Nombre :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel6.setText("Apellido :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 70, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel7.setText("Telefono :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 80, 20));
        jPanel2.add(Usua, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 130, -1));
        jPanel2.add(Apelli, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 130, -1));
        jPanel2.add(Nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 130, -1));
        jPanel2.add(Tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 130, -1));

        Cont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContActionPerformed(evt);
            }
        });
        jPanel2.add(Cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 130, -1));
        jPanel2.add(Conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 130, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel8.setText("Tipo de documento :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel9.setText("Numero :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 80, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel10.setText("Cuidad :");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 80, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel11.setText("Departamento :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel12.setText("Correo :");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel13.setText("Direccion :");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        CBXtipo_documento.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        CBXtipo_documento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "C.C", "T.I", "C.EXTRAN" }));
        jPanel2.add(CBXtipo_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 120, -1));

        Num.setText(" ");
        jPanel2.add(Num, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 120, -1));
        jPanel2.add(Ciud, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 120, -1));
        jPanel2.add(Dep, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 120, -1));
        jPanel2.add(Corr, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 120, -1));
        jPanel2.add(Direcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 220, 120, -1));

        Registrarse.setFont(new java.awt.Font("Ravie", 2, 18)); // NOI18N
        Registrarse.setText("Registrarse");
        Registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarseActionPerformed(evt);
            }
        });
        jPanel2.add(Registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 200, 40));

        Volver.setFont(new java.awt.Font("Ravie", 2, 18)); // NOI18N
        Volver.setText("Volver");
        Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverActionPerformed(evt);
            }
        });
        jPanel2.add(Volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 130, 40));

        jButton1.setText("jButton1");
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 740, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseActionPerformed
    
        
        Sql_usuarios modSql = new Sql_usuarios();
        Usuarios mod = new Usuarios();
        // se convierten las contraseña ingresadas en datos String ya que estas por defecto son ingresadas en un vector de datos char por asi decirlos.
        String contra = new String(Cont.getPassword());
        String contra2 = new String(Conf.getPassword());

        if (Nom.getText().equals("") || contra.equals("") || contra2.equals("") || Apelli.getText().equals("") || CBXtipo_documento.getSelectedItem().toString().equals("Selecciona") || Num.getText().equals("") || Corr.getText().equals("") || Dep.getText().equals("") || Ciud.getText().equals("") || Direcc.getText().equals("") || Tel.getText().equals("") || Usua.getText().equals("") ){
            JOptionPane.showMessageDialog(null, "Por favor no dejar campos vacios");

        } else {

            if (contra.equals(contra2)) {

                if (modSql.existenumero(Num.getText()) == 0) {

                    // se estan pasando todos los datos al mod(modelo)        
                    mod.setNombre(Nom.getText());
                    mod.setApellido(Apelli.getText());
                    mod.setTipodocumento(CBXtipo_documento.getSelectedItem().toString());
                    mod.setDocumento(Num.getText());
                    mod.setUsuario(Usua.getText());
                    mod.setContraseña(contra);
                    mod.setCorreo(Corr.getText());
                    mod.setDepartamento(Dep.getText());
                    mod.setMunicipio(Ciud.getText());
                    mod.setTelefono(Tel.getText());
                    mod.setDireccion(Direcc.getText());
                    mod.setTipo(2);
                    // hacemos la comprobacion si los datos fueron ingresados a la base de datos por medio de un if.        
                    if (modSql.registrar(mod)) {

                        JOptionPane.showMessageDialog(null, "El registro fue todo un Exito");

                    } else {
                        JOptionPane.showMessageDialog(null, "Error al guardar");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "El numero de documento ya esta registrado");
                }

            } else {
                JOptionPane.showMessageDialog(null, "La Contraseña no coincide");

            }
        }  
        
        
    }//GEN-LAST:event_RegistrarseActionPerformed

    private void VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverActionPerformed
      
        this.dispose();
        Inicio run= new Inicio();
        run.setVisible(true);
    }//GEN-LAST:event_VolverActionPerformed

    private void ContActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apelli;
    private javax.swing.JComboBox<String> CBXtipo_documento;
    private javax.swing.JTextField Ciud;
    private javax.swing.JPasswordField Conf;
    private javax.swing.JPasswordField Cont;
    private javax.swing.JTextField Corr;
    private javax.swing.JTextField Dep;
    private javax.swing.JTextField Direcc;
    private javax.swing.JTextField Nom;
    private javax.swing.JTextField Num;
    private javax.swing.JButton Registrarse;
    private javax.swing.JTextField Tel;
    private javax.swing.JTextField Usua;
    private javax.swing.JButton Volver;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
